# Welcome to Jekyll!
#

# Site settings
title: Farm 6 Media
description: |
  Graphic Design * Content * Web Development
owner: Farm 6 Media # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: info@farm6.net
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://farm6media.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
